---
apiVersion: v1
kind: Service
metadata:
  name: wol 
spec:
  type: NodePort 
  selector:
    app: wol 
  ports: 
  - name: "tcp-port" 
    port: 8880 
    targetPort: 8880 
  externalIPs:
  - 192.168.0.211
  - 192.168.0.221
  - 192.168.0.222
  - 192.168.0.223
  - 192.168.0.224
